[workspace]
resolver = "2"

members = [
    "aoc_util", "day00",
    "day01", "day02", "day03", "day04", "day05", "day06", "day07", "day08", "day09", "day10",
    "day11", "day14", "day15"
]

[profile.bench]
debug = true
